FMS.Website/Controllers/RptCcfController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FMS.BusinessObject.Dto;
using FMS.BusinessObject.Inputs;
using FMS.Contract.BLL;
using FMS.Core;
using FMS.Utils;
using FMS.Website.Models;
using AutoMapper;
using DocumentFormat.OpenXml.Spreadsheet;
using SpreadsheetLight;

namespace FMS.Website.Controllers
{
    public class RptCcfController : BaseController
    {
        //
        // GET: /RptCcf/

        #region --------- Field and Constructor --------------

        private Enums.MenuList _mainMenu;
        private IPageBLL _pageBLL;
        private IRptCcfBLL _rptCcfBLL;
        private IComplaintCategoryBLL _rptComplaintBLL;
        private ISettingBLL _settingBLL;

        public RptCcfController(IPageBLL pageBll, IRptCcfBLL rptCcfBLL, ISettingBLL SettingBLL, IComplaintCategoryBLL rptComplaintBLL) 
            : base(pageBll, Core.Enums.MenuList.RptCcf)
        {
            _pageBLL = pageBll;
            _rptCcfBLL = rptCcfBLL;
            _rptComplaintBLL = rptComplaintBLL;
            _settingBLL = SettingBLL;
            _mainMenu = Enums.MenuList.RptExecutiveSummary;
        }

        #endregion

        public ActionResult Index()
        {
            var model = new RptCCFModel();
            var input = Mapper.Map<RptCCFInput>(model.SearchView);
            var data = _rptCcfBLL.GetRptCcf(input);
            model.MainMenu = _mainMenu;
            model.TitleForm = "CCF Report";
            model.TitleExport = "ExportCCF";
            model.CurrentLogin = CurrentUser;
            model.CurrentPageAccess = CurrentPageAccess;
            var settingData = _settingBLL.GetSetting();

            model.RptCCFItem = Mapper.Map<List<RptCCFItem>>(data);

            var listCategory = _rptComplaintBLL.GetComplaints().Select(x => new { x.MstComplaintCategoryId,x.CategoryName }).Distinct().OrderBy(x => x.MstComplaintCategoryId).ToList();
            var listCoordinator= _rptCcfBLL.GetRptCcfData().Where(x => x.CoordinatorName != null).Select(x => new { x.CoordinatorName }).Distinct().OrderBy(x => x.CoordinatorName).ToList();
            var listLocation = _rptCcfBLL.GetRptCcfData().Where(x=>x.LocationCity != null).Select(x => new { x.LocationCity }).Distinct().OrderBy(x => x.LocationCity).ToList();

            model.SearchView.Categorylist = new SelectList(listCategory, "MstComplaintCategoryId", "CategoryName");
            model.SearchView.Coordinatorlist = new SelectList(listCoordinator, "CoordinatorName", "CoordinatorName");
            model.SearchView.Locationlist = new SelectList(listLocation, "LocationCity", "LocationCity");
            
            return View(model);
        }

        [HttpPost]
        public PartialViewResult FilterCCF(RptCCFModel model)
        {
            model.RptCCFItem = GetCCFData(model.SearchView);
            var input = Mapper.Map<RptCCFInput>(model.SearchView);
            return PartialView("_ListCcf", model);
        }

        private List<RptCCFItem> GetCCFData(RptCCFSearchView filter = null)
        {
            if (filter == null)
            {
                //Get All
                var data = _rptCcfBLL.GetRptCcf(new RptCCFInput());
                return Mapper.Map<List<RptCCFItem>>(data);
            }

            //getbyparams
            var input = Mapper.Map<RptCCFInput>(filter);

            var dbData = _rptCcfBLL.GetRptCcf(input);
            return Mapper.Map<List<RptCCFItem>>(dbData);
        }

        #region --------- Export --------------
        public string ExportCcfReportGenerateReport(RptCCFModel model = null)
        {
            string pathFile = "";
            var input = Mapper.Map<RptCCFInput>(model.SearchView);
            pathFile = CreateXlsRptCCF(input);
            return pathFile;

        }
        public void GetExcelFile(string pathFile)
        {
            var newFile = new FileInfo(pathFile);
            var fileName = Path.GetFileName(pathFile);
            string attachment = string.Format("attachment; filename={0}", fileName);
            Response.Clear();
            Response.AddHeader("content-disposition", attachment);
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.WriteFile(newFile.FullName);
            Response.Flush();
            newFile.Delete();
            Response.End();

        }
        private string CreateXlsRptCCF(RptCCFInput input)
        {
            //get data
            List<RptCCFDto> data = _rptCcfBLL.GetRptCcf(input);
            var listData = Mapper.Map<List<RptCCFItem>>(data);

            var slDocument = new SLDocument();

            //title
            slDocument.SetCellValue(1, 1, "CCF Report Data");
            slDocument.MergeWorksheetCells(1, 1, 1, 14);
            //create style
            SLStyle valueStyle = slDocument.CreateStyle();
            valueStyle.SetHorizontalAlignment(HorizontalAlignmentValues.Center);
            valueStyle.Font.Bold = true;
            valueStyle.Font.FontSize = 18;
            slDocument.SetCellStyle(1, 1, valueStyle);

            //create header
            slDocument = CreateHeaderExcelDashboard(slDocument);

            //create data
            slDocument = CreateDataExcelDashboard(slDocument, listData);

            var fileName = "RptCCF" + DateTime.Now.ToString("_yyyyMMddHHmmss") + ".xlsx";
            var path = Path.Combine(Server.MapPath(Constans.UploadPath), fileName);

            slDocument.SaveAs(path);

            return path;

        }

        private SLDocument CreateHeaderExcelDashboard(SLDocument slDocument)
        {
            int iRow = 2;

            slDocument.SetCellValue(iRow, 1, "Complaint Number");
            slDocument.SetCellValue(iRow, 2, "Police Number");
            slDocument.SetCellValue(iRow, 3, "Police Number GS (Ganti Sementara)");
            slDocument.SetCellValue(iRow, 4, "Location City");
            slDocument.SetCellValue(iRow, 5, "Category");
            slDocument.SetCellValue(iRow, 6, "Coordinator");
            slDocument.SetCellValue(iRow, 7, "Coordinator Name");
            slDocument.SetCellValue(iRow, 8, "Created By");
            slDocument.SetCellValue(iRow, 9, "Created Date");
            slDocument.SetCellValue(iRow, 10, "Close Date");
            slDocument.SetCellValue(iRow, 11, "Status");
            slDocument.SetCellValue(iRow, 12, "Vendor Name");
            slDocument.SetCellValue(iRow, 13, "Late Respon Time Coordinator");
            slDocument.SetCellValue(iRow, 14, "Late Respon Time Vendor");

            SLStyle headerStyle = slDocument.CreateStyle();
            headerStyle.Alignment.Horizontal = HorizontalAlignmentValues.Center;
            headerStyle.Font.Bold = true;
            headerStyle.Border.LeftBorder.BorderStyle = BorderStyleValues.Thin;
            headerStyle.Border.RightBorder.BorderStyle = BorderStyleValues.Thin;
            headerStyle.Border.TopBorder.BorderStyle = BorderStyleValues.Thin;
            headerStyle.Border.BottomBorder.BorderStyle = BorderStyleValues.Thin;
            headerStyle.Fill.SetPattern(PatternValues.Solid, System.Drawing.Color.LightGray, System.Drawing.Color.LightGray);

            slDocument.SetCellStyle(iRow, 1, iRow, 14, headerStyle);

            return slDocument;

        }

        private SLDocument CreateDataExcelDashboard(SLDocument slDocument, List<RptCCFItem> listData)
        {
            int iRow = 3; //starting row data

            foreach (var data in listData)
            {
                slDocument.SetCellValue(iRow, 1, data.DocumentNumber);
                slDocument.SetCellValue(iRow, 2, data.PoliceNumber);
                slDocument.SetCellValue(iRow, 3, data.PoliceNumberGS);
                slDocument.SetCellValue(iRow, 4, data.LocationCity);
                slDocument.SetCellValue(iRow, 5, data.ComplaintCategoryName);
                slDocument.SetCellValue(iRow, 6, data.ComplaintCategoryRole);
                slDocument.SetCellValue(iRow, 7, data.CoordinatorName);
                slDocument.SetCellValue(iRow, 8, data.CreatedBy);
                slDocument.SetCellValue(iRow, 9, data.CreatedDate.ToString("dd-MMM-yyyy"));
                if (data.DocumentStatus == Enums.DocumentStatus.Completed)
                {
                    slDocument.SetCellValue(iRow, 10, data.ModifiedDate.Value.ToString("dd-MMM-yyyy"));
                }
                else
                {
                    slDocument.SetCellValue(iRow, 10, "");
                }
                slDocument.SetCellValue(iRow, 11, data.DocumentStatus.ToString());
                slDocument.SetCellValue(iRow, 12, data.Vendor);
                slDocument.SetCellValue(iRow, 13, data.CoordinatorKPI);
                slDocument.SetCellValue(iRow, 14, data.VendorKPI);

                iRow++;
            }

            //create style
            SLStyle valueStyle = slDocument.CreateStyle();
            valueStyle.Border.LeftBorder.BorderStyle = BorderStyleValues.Thin;
            valueStyle.Border.RightBorder.BorderStyle = BorderStyleValues.Thin;
            valueStyle.Border.TopBorder.BorderStyle = BorderStyleValues.Thin;
            valueStyle.Border.BottomBorder.BorderStyle = BorderStyleValues.Thin;

            slDocument.AutoFitColumn(1, 14);
            slDocument.SetCellStyle(3, 1, iRow - 1, 14, valueStyle);

            return slDocument;
        }

        #endregion
    }
}

FMS.Website/Views/RptCcf/Index.cshtml
@using FMS.Core;
@model FMS.Website.Models.RptCCFModel

@{
    ViewBag.Title = Model.TitleForm;
}

<div class="opt-content clearfloat">
    <h5 class="title-page">@ViewBag.Title</h5>
    @if (Model.CurrentPageAccess.ReadAccess == true)
    {
        <a href="#!" class="btn btn-primary line" id="btnExport" title="Export To Excel" onclick="ExportXls()">
            <i class="fa fa-upload"></i> Export
        </a>
    }
</div>
<section class="content">
    <div class="wpanel">
        <p>@Model.ErrorMessage</p>
        <div class="row">
            @using (Ajax.BeginForm("FilterCCF", "RptCcf",
                new AjaxOptions
                {
                    HttpMethod = "POST",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "contenttable",
                    OnComplete = "setupDataTables",
                    OnBegin = "LoadingShow",
                    OnSuccess = "LoadingHide",
                    OnFailure = "LoadingHide",
                }))
            {
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label">Period From</label>
                        <div class="input-group date" id="FromDate">
                            @Html.TextBoxFor(model => model.SearchView.PeriodFrom, "{0:dd-MMM-yyyy}", new { @class = "form-control date", @placeholder = "From", @id = "From_Date" })
                            <span class="input-group-addon btn btn-primary">
                                <i class="fa fa-calendar "></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label">Period To</label>
                        <div class="input-group date" id="FromDate">
                            @Html.TextBoxFor(model => model.SearchView.PeriodTo, "{0:dd-MMM-yyyy}", new { @class = "form-control date", @placeholder = "To", @id = "To_Date" })
                            <span class="input-group-addon btn btn-primary">
                                <i class="fa fa-calendar "></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="">Complaint Category</label>
                        @Html.DropDownListFor(model => model.SearchView.Category, Model.SearchView.Categorylist, "ALL", new { @class = "form-control select" })
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="">Coordinator Name</label>
                        @Html.DropDownListFor(model => model.SearchView.Coordinator, Model.SearchView.Coordinatorlist, "ALL", new { @class = "form-control select" })
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="">Location City</label>
                        @Html.DropDownListFor(model => model.SearchView.Location, Model.SearchView.Locationlist, "ALL", new { @class = "form-control select" })
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="">Late Respone Time Coordinator</label>
                        @Html.TextBoxFor(model => model.SearchView.CoorKPI, new { @class = "form-control text"})
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="">Late Respone Time Vendor</label>
                        @Html.TextBoxFor(model => model.SearchView.VendorKPI, new { @class = "form-control text"})
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-12">
                    <button id="btn-filter" type="submit" class="btn btn-primary">Filter</button>
                    <button id="btn-reset" type="button" class="btn btn-default">Reset</button>
                </div>
            }
        </div>
    </div>
    <div id="contenttable" class="wpanel">
        @Html.Partial("_ListCcf")
    </div>
</section>
<div id="LoadingModal" class="modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div align="center">
                    <img src="~/Content/img/loader2.gif" id="imgLoader" style="display:block" />
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/CCF.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script type="text/javascript">
    function LoadingShow() {
        $('#LoadingModal').show();
    }
    function LoadingHide() {
        $('#LoadingModal').hide();
    }
    function ExportXls() {
        console.log('Submitting');
        var url = '@Url.Action("ExportCcfReportGenerateReport", "RptCcf")';
        var getFileUrl = '@Url.Action("GetExcelFile", "RptCcf")';
        console.log(url);
        var objToUpload =
			{
			    SearchView: {
			        PeriodFrom: $('#From_Date').val(),
			        PeriodTo: $('#To_Date').val(),
			        Category: $('#SearchView_Category').val(),
			        Coordinator: $('#SearchView_Coordinator').val(),
			        Location: $('#SearchView_Location').val(),
			        CoorKPI:$('#SearchView_CoorKPI').val(),
			        VendorKPI:$('#SearchView_VendorKPI').val(),
			    }
			};
        $.ajax({
            url: url,
            data: JSON.stringify(objToUpload),
            contentType: 'application/json; charset=utf-8',
            beforeSend: function () {
                $('#LoadingModal').show();
            },
            success: function (response, status, jqxhr) {
                console.log("DONE");
                window.location = getFileUrl + "?pathFile=" + response;
                $('#LoadingModal').hide();
            },
            error: function (jqhxr) {
                console.log("ERROR");
                console.log(jqhxr.responseText);
                $('#LoadingModal').hide();
            },
            type: 'POST'
        });

    }
    function setupDataTables() {
        // DataTable
        var table = $('#tbRptCcf').DataTable({
            "dom": 'lf<"table-overflow"t>pi',
            orderCellsTop: true
        });

        // Apply the search
        table.columns().eq(0).each(function (colIdx) {
            $('input', $('.filters th')[colIdx]).on('keyup change', function () {
                table
                    .column(colIdx)
                    .search(this.value)
                    .draw();
            });
        });
    }

    $(document).on('click', '#btn-reset', function () {
        var todayDate = new Date();
        todayDate.setHours(00, 00, 00, 00);
        var months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
        var todayDatestr = todayDate.getDate() + '-' + (months[todayDate.getMonth()]) + '-' + todayDate.getFullYear();

        var date = new Date();
        date.setDate(1);
        date.setHours(00, 00, 00, 00);
        var months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
        var datestr = date.getDate() + '-' + (months[date.getMonth()]) + '-' + date.getFullYear();


        $('#From_Date').val(todayDatestr);
        $('#To_Date').val(todayDatestr);

        $(".select").val('');
        $(".text").val('');

        $("#btn-filter").trigger('click');
    });

    $(function () {
        setupDataTables();
        $("#btn-reset").trigger('click');
    });
</script>

FMS.Website/Views/RptCcf/_ListCcf.cshtml
@using FMS.Core
@model FMS.Website.Models.RptCCFModel

<table id="tbRptCcf" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Complaint Number</th>
            <th>Police Number</th>
            <th>Police Number Non GS (Ganti Sementara)</th>
            <th>Location City</th>
            <th>Category</th>
            <th>Coordinator</th>
            <th>Coordinator Name</th>
            <th>Created By</th>
            <th>Created Date</th>
            <th>Close Date</th>
            <th>Status</th>
            <th>Vendor Name</th>
            <th>Late Respon Time Coordinator</th>
            <th>Late Respon Time Vendor</th>
        </tr>
    </thead>
    <thead class="filters">
        <tr>
            <th><input style="border-radius: 5px; text-align: center;" type="text" class="form-control" placeholder="search"></th>
            <th><input style="border-radius: 5px; text-align: center;" type="text" class="form-control" placeholder="search"></th>
            <th><input style="border-radius: 5px; text-align: center;" type="text" class="form-control" placeholder="search"></th>
            <th><input style="border-radius: 5px; text-align: center;" type="text" class="form-control" placeholder="search"></th>
            <th><input style="border-radius: 5px; text-align: center;" type="text" class="form-control" placeholder="search"></th>
            <th><input style="border-radius: 5px; text-align: center;" type="text" class="form-control" placeholder="search"></th>
            <th><input style="border-radius: 5px; text-align: center;" type="text" class="form-control" placeholder="search"></th>
            <th><input style="border-radius: 5px; text-align: center;" type="text" class="form-control" placeholder="search"></th>
            <th><input style="border-radius: 5px; text-align: center;" type="text" class="form-control" placeholder="search"></th>
            <th><input style="border-radius: 5px; text-align: center;" type="text" class="form-control" placeholder="search"></th>
            <th><input style="border-radius: 5px; text-align: center;" type="text" class="form-control" placeholder="search"></th>
            <th><input style="border-radius: 5px; text-align: center;" type="text" class="form-control" placeholder="search"></th>
            <th><input style="border-radius: 5px; text-align: center;" type="text" class="form-control" placeholder="search"></th>
            <th><input style="border-radius: 5px; text-align: center;" type="text" class="form-control" placeholder="search"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.RptCCFItem)
        {
            <tr>
                <td>@Html.Raw(data.DocumentNumber)</td>
                <td>@Html.Raw(data.PoliceNumber)</td>
                <td>@Html.Raw(data.PoliceNumberGS)</td>
                <td>@Html.Raw(data.LocationCity)</td>
                <td>@Html.Raw(data.ComplaintCategoryName)</td>
                <td>@Html.Raw(data.ComplaintCategoryRole)</td>
                <td>@Html.Raw(data.CoordinatorName)</td>
                <td>@Html.Raw(data.CreatedBy)</td>
                <td>@Html.Raw(data.CreatedDate.ToString("dd-MMM-yyyy"))</td>
                @if (data.DocumentStatus == Enums.DocumentStatus.Completed)
                {
                    <td>@Html.Raw(data.ModifiedDate.Value.ToString("dd-MMM-yyyy"))</td>
                }
                else
                {
                    <td>&nbsp;</td>
                }
                <td>@Html.Raw(data.DocumentStatus)</td>
                <td>@Html.Raw(data.Vendor)</td>
                <td>@Html.Raw(data.CoordinatorKPI)</td>
                <td>@Html.Raw(data.VendorKPI)</td>
            </tr>
        }
    </tbody>
</table>