FMS.Website/Controllers/MstEmployeeController.cs
using AutoMapper;
using FMS.BusinessObject;
using FMS.Contract.BLL;
using FMS.BusinessObject.Dto;
using FMS.Core;
using FMS.Website.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using SpreadsheetLight;
using DocumentFormat.OpenXml.Spreadsheet;
using FMS.Website.Utility;
using FMS.BusinessObject.Inputs;

namespace FMS.Website.Controllers
{
    public class MstEmployeeController : BaseController
    {
        private IEmployeeBLL _employeeBLL;
        private Enums.MenuList _mainMenu;

        //
        // GET: /MstEmployee/
        public MstEmployeeController(IPageBLL pageBll, IEmployeeBLL employeeBLL) : base(pageBll, Enums.MenuList.MasterEmployee)
        {
            _employeeBLL = employeeBLL;
            _mainMenu = Enums.MenuList.MasterData;
        }

        public ActionResult Index()
        {
            var model = new EmployeeModel();
            model.MainMenu = _mainMenu;
            model.CurrentLogin = CurrentUser;
            model.CurrentPageAccess = CurrentPageAccess;
            model.WriteAccess = CurrentPageAccess.WriteAccess == true ? 1 : 0;
            model.ReadAccess = CurrentPageAccess.ReadAccess == true ? 1 : 0;
            return View(model);
        }

        [HttpPost]
        public ActionResult SearchEmployeeAjax(DTParameters<EmployeeModel> param)
        {
            var model = param;

            var data = model != null ? SearchDataEmployee(model) : SearchDataEmployee();
            DTResult<EmployeeItem> result = new DTResult<EmployeeItem>();
            result.draw = param.Draw;
            result.recordsFiltered = data.Count;
            result.recordsTotal = data.Count;
            //param.TotalData = data.Count;
            //if (param != null && param.Start > 0)
            //{
            IEnumerable<EmployeeItem> dataordered;
            dataordered = data;
            if (param.Order.Length > 0)
            {
                foreach (var ordr in param.Order)
                {
                    if (ordr.Column == 0)
                    {
                        continue;
                    }
                    dataordered = EmployeeDataOrder(EmployeeDataOrderByIndex(ordr.Column), ordr.Dir, dataordered);
                }
            }
            data = dataordered.ToList();
            data = data.Skip(param.Start).Take(param.Length).ToList();

            //}
            result.data = data;

            return Json(result);
        }

        private List<EmployeeItem> SearchDataEmployee(DTParameters<EmployeeModel> searchView = null)
        {
            var param = new EmployeeParamInput();
            param.Status = searchView.StatusSource == "False" ? false : true;
            param.EmployeeId = searchView.EmployeeId;
            param.FormalName = searchView.FormalName;
            param.PositionTitle = searchView.PositionTitle;
            param.Division = searchView.Division;
            param.Directorate = searchView.Directorate;
            param.Address = searchView.Address;
            param.City = searchView.City;
            param.BaseTown = searchView.BaseTown;
            param.Company = searchView.Company;
            param.CostCenter = searchView.CostCenter;
            param.GroupLevel = searchView.GroupLevel;
            param.EmailAddress = searchView.EmailAddress;
            param.FlexPoint = searchView.FlexPoint;
            param.Table = searchView.Table;
            var data = _employeeBLL.GetEmployeeByParam(param);
            return Mapper.Map<List<EmployeeItem>>(data);
        }

        private IEnumerable<EmployeeItem> EmployeeDataOrder(string column, DTOrderDir dir, IEnumerable<EmployeeItem> data)
        {

            switch (column)
            {
                case "EmployeeId": return dir == DTOrderDir.ASC ? data.OrderBy(x => x.EMPLOYEE_ID).ToList() : data.OrderByDescending(x => x.EMPLOYEE_ID).ToList();
                case "FormalName": return dir == DTOrderDir.ASC ? data.OrderBy(x => x.FORMAL_NAME).ToList() : data.OrderByDescending(x => x.FORMAL_NAME).ToList();
                case "PositionTitle": return dir == DTOrderDir.ASC ? data.OrderBy(x => x.POSITION_TITLE).ToList() : data.OrderByDescending(x => x.POSITION_TITLE).ToList();
                case "Division": return dir == DTOrderDir.ASC ? data.OrderBy(x => x.DIVISON).ToList() : data.OrderByDescending(x => x.DIVISON).ToList();
                case "Directorate": return dir == DTOrderDir.ASC ? data.OrderBy(x => x.DIRECTORATE).ToList() : data.OrderByDescending(x => x.DIRECTORATE).ToList();
                case "Address": return dir == DTOrderDir.ASC ? data.OrderBy(x => x.ADDRESS).ToList() : data.OrderByDescending(x => x.ADDRESS).ToList();
                case "City": return dir == DTOrderDir.ASC ? data.OrderBy(x => x.CITY).ToList() : data.OrderByDescending(x => x.CITY).ToList();
                case "BaseTown": return dir == DTOrderDir.ASC ? data.OrderBy(x => x.BASETOWN).ToList() : data.OrderByDescending(x => x.BASETOWN).ToList();
                case "Company": return dir == DTOrderDir.ASC ? data.OrderBy(x => x.COMPANY).ToList() : data.OrderByDescending(x => x.COMPANY).ToList();
                case "CostCenter": return dir == DTOrderDir.ASC ? data.OrderBy(x => x.COST_CENTER).ToList() : data.OrderByDescending(x => x.COST_CENTER).ToList();
                case "GroupLevel": return dir == DTOrderDir.ASC ? data.OrderBy(x => x.GROUP_LEVEL).ToList() : data.OrderByDescending(x => x.GROUP_LEVEL).ToList();
                case "EmailAddress": return dir == DTOrderDir.ASC ? data.OrderBy(x => x.EMAIL_ADDRESS).ToList() : data.OrderByDescending(x => x.EMAIL_ADDRESS).ToList();
                case "FlexPoint": return dir == DTOrderDir.ASC ? data.OrderBy(x => x.FLEX_POINT).ToList() : data.OrderByDescending(x => x.FLEX_POINT).ToList();

            }
            return null;
        }

        private string EmployeeDataOrderByIndex(int index)
        {
            Dictionary<int, string> columnDict = new Dictionary<int, string>();
            columnDict.Add(1, "EmployeeId");
            columnDict.Add(2, "FormalName");
            columnDict.Add(3, "PositionTitle");
            columnDict.Add(4, "Division");
            columnDict.Add(5, "Directorate");
            columnDict.Add(6, "Address");
            columnDict.Add(7, "City");
            columnDict.Add(8, "BaseTown");
            columnDict.Add(9, "Company");
            columnDict.Add(10, "CostCenter");
            columnDict.Add(11, "GroupLevel");
            columnDict.Add(12, "EmailAddress");
            columnDict.Add(13, "FlexPoint");


            return columnDict[index];
        }

        public EmployeeItem listdata2(EmployeeItem model,string id)
        {
            var list_position_title = _employeeBLL.GetEmployee().Select(x => new { x.POSITION_TITLE }).ToList().Distinct().OrderBy(x => x.POSITION_TITLE);
            model.PositionTitleList = new SelectList(list_position_title, "POSITION_TITLE", "POSITION_TITLE");
            var list_divison_title = _employeeBLL.GetEmployee().Select(x => new { x.DIVISON }).ToList().Distinct().OrderBy(x => x.DIVISON);
            model.DivisonList = new SelectList(list_divison_title, "DIVISON", "DIVISON");
            var list_directorate = _employeeBLL.GetEmployee().Select(x => new { x.DIRECTORATE }).ToList().Distinct().OrderBy(x => x.DIRECTORATE);
            model.DirectorateList = new SelectList(list_directorate, "DIRECTORATE", "DIRECTORATE");
            var list_city = _employeeBLL.GetEmployee().Select(x => new { x.CITY }).ToList().Distinct().OrderBy(x => x.CITY);
            model.CityList = new SelectList(list_city, "CITY", "CITY");
            var list_basetown = _employeeBLL.GetEmployee().Select(x => new { x.BASETOWN }).ToList().Distinct().OrderBy(x => x.BASETOWN);
            model.BaseTownList = new SelectList(list_basetown, "BASETOWN", "BASETOWN");
            var list_company = _employeeBLL.GetEmployee().Select(x => new { x.COMPANY }).ToList().Distinct().OrderBy(x => x.COMPANY);
            model.CompanyList = new SelectList(list_company, "COMPANY", "COMPANY");
            var list_group_level = _employeeBLL.GetEmployee().Select(x => new { x.GROUP_LEVEL }).ToList().Distinct().OrderBy(x => x.GROUP_LEVEL);
            model.GroupLevelList = new SelectList(list_group_level, "GROUP_LEVEL", "GROUP_LEVEL");
            var list_flext_point = _employeeBLL.GetEmployee().Select(x => new { x.FLEX_POINT }).ToList().Distinct().OrderBy(x => x.FLEX_POINT);
            model.FlexPointlList = new SelectList(list_flext_point, "FLEX_POINT", "FLEX_POINT");
            var list_address = _employeeBLL.GetEmployee().Select(x => new { x.ADDRESS,x.CITY}).ToList().Distinct().Where(x => x.CITY == id).OrderBy(x => x.ADDRESS);
            model.AddressList = new SelectList(list_address, "ADDRESS", "ADDRESS");
            return model;
        }

        public EmployeeItem listdata(EmployeeItem model, string id)
        {
            
            var list_position_title = _employeeBLL.GetEmployee().Select(x => new { x.POSITION_TITLE }).ToList().Distinct().OrderBy(x => x.POSITION_TITLE);
            model.PositionTitleList = new SelectList(list_position_title, "POSITION_TITLE", "POSITION_TITLE");
            var list_divison_title = _employeeBLL.GetEmployee().Select(x => new { x.DIVISON }).ToList().Distinct().OrderBy(x => x.DIVISON);
            model.DivisonList = new SelectList(list_divison_title, "DIVISON", "DIVISON");
            var list_directorate = _employeeBLL.GetEmployee().Select(x => new { x.DIRECTORATE }).ToList().Distinct().OrderBy(x => x.DIRECTORATE);
            model.DirectorateList = new SelectList(list_directorate, "DIRECTORATE", "DIRECTORATE");
            var list_city = _employeeBLL.GetEmployee().Select(x => new { x.CITY, x.BASETOWN }).ToList().Distinct().Where(x => x.BASETOWN == id).OrderBy(x => x.CITY);
            model.CityList = new SelectList(list_city, "CITY", "CITY");

FMS.Website/Views/MstEmployee/Create.cshtml
@using FMS.Core;
@model FMS.Website.Models.EmployeeItem

<div class="opt-content clearfloat">
    <h5 class="title-page">Master Data Employee Create</h5>
</div>
<section class="content" ng-controller="MSTCCtrl" ng-init="init()">

    <div class="wpanel">
        @using (Html.BeginForm("Create", "MstEmployee"))
        {
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Employee ID<span class="red">*</span></label>
                        <div class="row">
                            <div class="col-md-2">
                                @Html.HiddenFor(model => model.IS_ACTIVE)
                                @Html.TextBoxFor(model => model.EMPLOYEE_CODE, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.EMPLOYEE_ID, new { @class = "form-control", @maxlength = "8", @autocomplete = "off" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Employee Name<span class="red">*</span></label>
                        @Html.TextBoxFor(model => model.FORMAL_NAME, new { @class = "form-control", @autocomplete = "off", @required="required" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Position<span class="red"></span></label>
                        @Html.TextBoxFor(model => model.POSITION_TITLE, new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Division<span class="red">*</span></label>
                        @Html.DropDownListFor(model => model.DIVISON, Model.DivisonList, "-- Please Select --", new { @class = "form-control", @required = "required" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Directorate<span class="red">*</span></label>
                        @Html.DropDownListFor(model => model.DIRECTORATE, Model.DirectorateList, "-- Please Select --", new { @class = "form-control", @required = "required" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Basetown<span class="red">*</span></label>
                        @Html.DropDownListFor(model => model.BASETOWN, Model.BaseTownList, "-- Please Select --", new { @class = "form-control", @id = "BaseTownEmployee", @required = "required" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">City<span class="red">*</span></label>
                        @Html.TextBoxFor(model => model.CITY, new { @class = "form-control", @required = "required", @readonly = "readonly" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Address<span class="red">*</span></label>
                        @Html.TextBoxFor(model => model.ADDRESS, new { @class = "form-control", @required = "required", @readonly = "readonly" })
                        @*@Html.TextBoxFor(model => model.ADDRESS, new { @class = "form-control", @autocomplete = "off" })*@
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Company<span class="red">*</span></label>
                        @Html.DropDownListFor(model => model.COMPANY, Model.CompanyList, "-- Please Select --", new { @class = "form-control", @required = "required" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Cost Center<span class="red">*</span></label>
                        @Html.TextBoxFor(model => model.COST_CENTER, new { @class = "form-control", @autocomplete = "off", @required = "required" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Group Level<span class="red">*</span></label>
                        @Html.DropDownListFor(model => model.GROUP_LEVEL, Model.GroupLevelList, "-- Please Select --", new { @class = "form-control", @required = "required" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Email Address<span class="red"></span></label>
                        @Html.TextBoxFor(model => model.EMAIL_ADDRESS, new { @class = "form-control", @autocomplete = "off" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Flex Point<span class="red"></span></label>
                        @Html.TextBoxFor(model => model.FLEX_POINT, new { @class = "form-control", @autocomplete = "off", @readonly = "readonly" })
                        @*@Html.DropDownListFor(model => model.FLEX_POINT, Model.FlexPointlList, "-- Please Select --", new { @class = "form-control" })*@
                    </div>
                </div>
                <div class="col-md-12">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <a href="@Url.Action("Index", "MstEmployee" )" class="btn btn-default">Back</a>
                </div>
            </div>
        }
    </div>
</section>

<script>
    $(document).ready(function () {
        $("#IS_ACTIVE").val("True");
    });
    $("#BaseTownEmployee").change(function () {
        //alert($("#AddressEmployee").val());

        $.ajax({
            url: "GetBaseTownDataJson",
            cahce: false,
            type: "post",
            data: { "id": $("#BaseTownEmployee").val() },
            success: function (result) {
                console.log(result);
                $("#AddressEmployee").empty();
                $('#address').empty();
                optionArray = [];
                $.each(result['CityList'], function (i, option) {
                    optionArray[i] = "<option value='" + option.Value + "'>" + option.Text + "</option>";
                    $('#AddressEmployee').append($('<option></option>').val(option.Value).html(option.Text));
                    $('#CITY').val(option.Value);
                });
                $.each(result['AddressList'], function (i, option) {
                    optionArray[i] = "<option value='" + option.Value + "'>" + option.Text + "</option>";
                    $('#address').append($('<option></option>').val(option.Value).html(option.Text));
                    $('#ADDRESS').val(option.Value);
                });
            }
        });
    });
</script>

FMS.Website/Views/MstEmployee/Detail.cshtml
@using FMS.Core;
@model FMS.Website.Models.EmployeeItem

<div class="opt-content clearfloat">
    <h5 class="title-page">Master Data Employee</h5>
</div>
<section class="content" ng-controller="MSTCCtrl" ng-init="init()">

    <div class="wpanel">
        @using (Html.BeginForm("Edit", "MstEmployee"))
        {
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Employee ID<span class="red">*</span></label>
                        @Html.HiddenFor(model => model.CREATED_BY)
                        @Html.HiddenFor(model => model.CREATED_DATE)
                        @Html.TextBoxFor(model => model.EMPLOYEE_ID, new { @class = "form-control", @maxlength = "9", @readonly = "readonly" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Employee Name<span class="red">*</span></label>
                        @Html.TextBoxFor(model => model.FORMAL_NAME, new { @class = "form-control", @autocomplete = "off", @disabled = "disabled" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Position<span class="red">*</span></label>
                        @Html.DropDownListFor(model => model.POSITION_TITLE, Model.PositionTitleList, new { @class = "form-control", @disabled = "disabled" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Division<span class="red">*</span></label>
                        @Html.DropDownListFor(model => model.DIVISON, Model.DivisonList, new { @class = "form-control", @disabled = "disabled" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Directorate<span class="red">*</span></label>
                        @Html.DropDownListFor(model => model.DIRECTORATE, Model.DirectorateList, new { @class = "form-control", @disabled = "disabled" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Basetown<span class="red">*</span></label>
                        @Html.DropDownListFor(model => model.BASETOWN, Model.BaseTownList, new { @class = "form-control", @disabled = "disabled" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">City<span class="red">*</span></label>
                        @Html.TextBoxFor(model => model.CITY, new { @class = "form-control", @id = "AddressEmployee", @required = "required", @disabled = "disabled" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Address<span class="red">*</span></label>
                        @Html.TextBoxFor(model => model.ADDRESS, new { @class = "form-control", @id = "address", @required = "required", @disabled = "disabled" })
                        @*@Html.TextBoxFor(model => model.ADDRESS, new { @class = "form-control", @autocomplete = "off" })*@
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Company<span class="red">*</span></label>
                        @Html.DropDownListFor(model => model.COMPANY, Model.CompanyList, new { @class = "form-control", @disabled = "disabled" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Cost Center<span class="red">*</span></label>
                        @Html.TextBoxFor(model => model.COST_CENTER, new { @class = "form-control", @autocomplete = "off", @disabled = "disabled" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Group Level<span class="red">*</span></label>
                        @Html.DropDownListFor(model => model.GROUP_LEVEL, Model.GroupLevelList, new { @class = "form-control", @disabled = "disabled" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Email Address<span class="red">*</span></label>
                        @Html.TextBoxFor(model => model.EMAIL_ADDRESS, new { @class = "form-control", @autocomplete = "off", @disabled = "disabled" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Flex Point<span class="red">*</span></label>
                        @Html.TextBoxFor(model => model.FLEX_POINT, new { @class = "form-control", @autocomplete = "off", @readonly = "readonly" })
                        @*@Html.DropDownListFor(model => model.FLEX_POINT, Model.FlexPointlList, new { @class = "form-control" })*@
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group" disabled = "disabled" >
                        <label class="control-label col-sm-2">Status <span class="red"></span></label>
                        <div class="form-control">
                            @Html.CheckBoxFor(model => model.IS_ACTIVE,new { @disabled = "disabled" })
                            @Html.Label("Active", new { @id = "lblStatus"})
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    @*<input type="submit" value="Save" class="btn btn-primary" />*@
                    <a href="@Url.Action("Index", "MstEmployee" )" class="btn btn-default">Back</a>
                </div>
            </div>
        }
    </div>
    <div id="changes" class="tab-pane">
        @Html.Partial("_ChangesLog");
    </div>
</section>
<script>
    $("#AddressEmployee").change(function () {
        //alert($("#AddressEmployee").val());

        $.ajax({
            url: "GetDataJson",
            cahce: false,
            type: "post",
            data: { "id": $("#AddressEmployee").val() },
            success: function (result) {
                console.log(result);
                $('#address').empty();
                optionArray = [];
                $.each(result['AddressList'], function (i, option) {
                    optionArray[i] = "<option value='" + option.Value + "'>" + option.Text + "</option>";
                    $('#address').append($('<option></option>').val(option.Value).html(option.Text));
                });
            }
        });
    });

    $(document).ready(function () {

        if ($('.title-page').html() == 'Master Data Employee') {
            $('#MstEmployeeMenu').addClass('active');
        }

        $('aside').animate({
            scrollTop: $("#MstEmployee").offset().top
        }, 1000);
    });
</script>

FMS.Website/Views/MstEmployee/Upload.cshtml
@model FMS.Website.Models.EmployeeModel
@using FMS.Core;

<div class="opt-content clearfloat">
    <h5 class="title-page">Master Data Employee Upload</h5>
</div>
<section class="content" ng-controller="MSTCCtrl" ng-init="init()">
    <div class="wpanel">
        @using (Html.BeginForm("Upload", "MstEmployee", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input-group">
                            <input type="file" id="upload" name="upload" class="form-control rounded-0 rounded-left" />
                            <span class="input-group-btn">
                                <button type="button" id="btnupload" value="upload" name="upload" class="btn btn-primary rounded-0 rounded-right">Generate</button>
                            </span>
                        </div>
                        <div>
                            Download template <a href="~/files_upload/masterEmployee.xlsx">here</a>
                        </div>
                    </div>
                </div>
            </div>
            <table id="example2" class="table table-bordered dataTables table-striped">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Employee ID</th>
                        <th>Formal Name</th>
                        <th>Position Title</th>
                        <th>Divison</th>
                        <th>Directorate</th>
                        <th>Address</th>
                        <th>City</th>
                        <th>Basetown</th>
                        <th>Company</th>
                        <th>Cost Center</th>
                        <th>Group Level</th>
                        <th>Email Address</th>
                        <th>Flex Point</th>
                    </tr>
                </thead>
                <tbody id="tb-upload-excel"></tbody>
            </table>
            <div class="row mt-2">
                <div class="col-md-12">
                    <button class="btn btn-primary" type="submit" id="btnSave">Save</button>
                    <a href="@Url.Action("Index","MstEmployee")" title="Cancel" class="btn">Cancel</a>
                </div>
            </div>
        }
    </div>
    <!-- /.row -->
</section>

<script type="text/javascript">

    $('#btnSave').prop('disabled', true);

    function createColumn(text) {
        return '<td>' + text + '</td>';
    }
    var uploaditems = [];

    function createColumnWithHiddenField(text, name) {
        return '<td><input type="hidden" name="' + name + '" value="' + text + '">' + text + '</td>';
    }

    function createColumnWithHiddenFieldDecimal(text, name) {
        return '<td><input type="hidden" name="' + name + '" value="' + text + '"><span class="decimal">' + text + '</span></td>';
    }
    $('#btnupload').click(function () {
        uploadXmlFile();
    });

    function uploadXmlFile() {
        var postUrl = '@Url.Action("UploadFile", "MstEmployee")';
        var fileName = $('[name="upload"]').val().trim();
        var pos = fileName.lastIndexOf('.');
        var extension = (pos <= 0) ? '' : fileName.substring(pos);
        if (extension != '.xlsx') {
            alert('Please browse a correct excel file to upload');
            return false;
        }

        var formData = new FormData();
        var totalFiles = document.getElementById("upload").files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = document.getElementById("upload").files[i];
            formData.append("upload", file);
        }
        $.ajax({
            type: "POST",
            url: postUrl,
            data: formData,
            dataType: 'html',
            contentType: false,
            processData: false,

            success: function (response) {
                $('#tb-upload-excel').html('');
                uploaditems = JSON.parse(response);
                var error = "";
                for (var i = 0; i < uploaditems.length; i++) {
                    var tr = '<tr>' +
                createColumn(i + 1) +
                 createColumnWithHiddenField(uploaditems[i].EMPLOYEE_ID, 'Model.Details[' + i + '].EMPLOYEE_ID') +
                createColumnWithHiddenField(uploaditems[i].FORMAL_NAME, 'Model.Details[' + i + '].FORMAL_NAME') +
                createColumnWithHiddenField(uploaditems[i].POSITION_TITLE, 'Model.Details[' + i + '].POSITION_TITLE') +
                createColumnWithHiddenField(uploaditems[i].DIVISON, 'Model.Details[' + i + '].DIVISON') +
                createColumnWithHiddenField(uploaditems[i].DIRECTORATE, 'Model.Details[' + i + '].DIRECTORATE') +
                createColumnWithHiddenField(uploaditems[i].ADDRESS, 'Model.Details[' + i + '].ADDRESS') +
                createColumnWithHiddenField(uploaditems[i].CITY, 'Model.Details[' + i + '].CITY') +
                createColumnWithHiddenField(uploaditems[i].BASETOWN, 'Model.Details[' + i + '].BASETOWN') +
                createColumnWithHiddenField(uploaditems[i].COMPANY, 'Model.Details[' + i + '].COMPANY') +
                createColumnWithHiddenField(uploaditems[i].COST_CENTER, 'Model.Details[' + i + '].COST_CENTER') +
                createColumnWithHiddenField(uploaditems[i].GROUP_LEVEL, 'Model.Details[' + i + '].GROUP_LEVEL') +
                createColumnWithHiddenField(uploaditems[i].EMAIL_ADDRESS, 'Model.Details[' + i + '].EMAIL_ADDRESS') +
                createColumnWithHiddenField(uploaditems[i].FLEX_POINT, 'Model.Details[' + i + '].FLEX_POINT') +
                '</tr>';
                    $('#tb-upload-excel').append(tr);
                    error += uploaditems[i].Message;
                }
               $('#btnSave').prop('disabled', false);
            }
        });
    };
</script>