FMS.Website/Controllers/RptExecutiveSummaryController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FMS.BusinessObject.Dto;
using FMS.BusinessObject.Inputs;
using FMS.Contract.BLL;
using FMS.Core;
using FMS.Utils;
using FMS.Website.Models;
using AutoMapper;
using DocumentFormat.OpenXml.Spreadsheet;
using SpreadsheetLight;
using SpreadsheetLight.Charts;

namespace FMS.Website.Controllers
{
    public class RptExecutiveSummaryController : BaseController
    {
        #region --------- Field and Constructor --------------

        private Enums.MenuList _mainMenu;
        private IPageBLL _pageBLL;
        private IExecutiveSummaryBLL _execSummBLL;
        private ISettingBLL _settingBLL;
        private ILocationMappingBLL _locationMappingBLL;
        private IGroupCostCenterBLL _groupCostCenterBLL;
        private IEmployeeBLL _employeeBLL;


        public RptExecutiveSummaryController(IPageBLL pageBll, IExecutiveSummaryBLL execSummBLL, ISettingBLL settingBLL, ILocationMappingBLL locationMappingBLL,
            IGroupCostCenterBLL groupCostCenterBLL, IEmployeeBLL EmployeeBLL)
            : base(pageBll, Core.Enums.MenuList.RptExecutiveSummary)
        {
            _pageBLL = pageBll;
            _execSummBLL = execSummBLL;
            _settingBLL = settingBLL;
            _locationMappingBLL = locationMappingBLL;
            _groupCostCenterBLL = groupCostCenterBLL;
            _employeeBLL = EmployeeBLL;
            _mainMenu = Enums.MenuList.RptExecutiveSummary;
        }

        #endregion

        #region --------- Set Data -----------------------

        public MultiSelectList GetFunctionsMultiSelectList()
        {
            var items = new List<SelectListItem>()
            {
                new SelectListItem() {Text = "Sales", Value = "Sales" },
                new SelectListItem() {Text = "Marketing", Value = "Marketing" },
                new SelectListItem() {Text = "Operations", Value = "Operations" },
                new SelectListItem() {Text = "Others", Value = "Others" }
            };

            return new MultiSelectList(items, "Value", "Text");
        }

        #endregion

        #region --------- Get Data Json -----------------------

        [HttpPost]
        public JsonResult GetVehicleDataVisual(int monthFrom, int? yearFrom)
        {
            var input = new VehicleGetByParamInput();
            input.MonthFrom = monthFrom;
            input.YearFrom = yearFrom == null ? 0 : yearFrom.Value;
            input.MonthTo = monthFrom;
            input.YearTo = yearFrom == null ? 0 : yearFrom.Value;
            if (CurrentUser.UserRole == Enums.UserRole.FinanceZone || CurrentUser.UserRole == Enums.UserRole.ComFinanceManager
                        || CurrentUser.UserRole == Enums.UserRole.Logistic || CurrentUser.UserRole == Enums.UserRole.OpsFinanceManager
                        || CurrentUser.UserRole == Enums.UserRole.LDManager)
            {
                input.VehicleType = "WTC";
            }
            else if (CurrentUser.UserRole == Enums.UserRole.HR || CurrentUser.UserRole == Enums.UserRole.HRManager)
            {
                input.VehicleType = "BENEFIT";
            }

            if (CurrentUser.UserRole == Enums.UserRole.FinanceZone || CurrentUser.UserRole == Enums.UserRole.ComFinanceManager)
            {
                input.Function = "Sales,Marketing";
            }
            else if (CurrentUser.UserRole == Enums.UserRole.OpsFinanceManager)
            {
                input.Function = "Operations";
            }
            else if (CurrentUser.UserRole == Enums.UserRole.Logistic || CurrentUser.UserRole == Enums.UserRole.LDManager)
            {
                input.Function = "Logistic";
            }
            var EmployeeList = _employeeBLL.GetEmployee().Where(x => x.IS_ACTIVE).ToList();
            var LocationMappingList = _locationMappingBLL.GetLocationMapping().Where(x => x.IsActive).ToList();
            if (CurrentUser.UserRole == Enums.UserRole.FinanceZone || CurrentUser.UserRole == Enums.UserRole.Logistic)
            {
                var GetCity = EmployeeList.Where(x => x.EMPLOYEE_ID == CurrentUser.EMPLOYEE_ID && x.IS_ACTIVE).FirstOrDefault();
                if (GetCity != null)
                {
                    var GetRegion = LocationMappingList.Where(x => (x.Location == null ? "" : x.Location.ToUpper()) == (GetCity.CITY == null ? "" : GetCity.CITY.ToUpper())).FirstOrDefault();
                    if (GetRegion != null)
                    {
                        input.ZoneId = GetRegion.ZoneSales;
                    }
                }
            }

            List<NoVehicleDto> data = _execSummBLL.GetNoOfVehicleData(input);

            var label1 = "BENEFIT (" + data.Where(x => (x.VEHICLE_TYPE == null ? "" : x.VEHICLE_TYPE.ToUpper()) == "BENEFIT").Sum(x => x.NO_OF_VEHICLE) + ")";
            var label2 = "WTC (" + data.Where(x => (x.VEHICLE_TYPE == null ? "" : x.VEHICLE_TYPE.ToUpper()) == "WTC").Sum(x => x.NO_OF_VEHICLE) + ")";

            var groupData = data.GroupBy(x => new { x.FUNCTION })
                .Select(p => new NoVehicleDto()
                {
                    FUNCTION = p.FirstOrDefault().FUNCTION,
                    NO_OF_VEHICLE_BENEFIT = p.Where(x => (x.VEHICLE_TYPE == null ? "" : x.VEHICLE_TYPE.ToUpper()) == "BENEFIT").Sum(c => c.NO_OF_VEHICLE),
                    NO_OF_VEHICLE_WTC = p.Where(x => (x.VEHICLE_TYPE == null ? "" : x.VEHICLE_TYPE.ToUpper()) == "WTC").Sum(c => c.NO_OF_VEHICLE),
                    LABEL1 = label1,
                    LABEL2 = label2
                }).OrderBy(x => x.FUNCTION).ToList();

            return Json(groupData);
        }

        [HttpPost]
        public JsonResult GetVehicleWtcDataVisual(int monthFrom, int? yearFrom)
        {
            var input = new VehicleWtcGetByParamInput();
            input.MonthFrom = monthFrom;
            input.YearFrom = yearFrom == null ? 0 : yearFrom.Value;
            input.MonthTo = monthFrom;
            input.YearTo = yearFrom == null ? 0 : yearFrom.Value;
            input.Function = "Sales,Marketing";
            if (CurrentUser.UserRole == Enums.UserRole.HR || CurrentUser.UserRole == Enums.UserRole.HRManager
                || CurrentUser.UserRole == Enums.UserRole.OpsFinanceManager || CurrentUser.UserRole == Enums.UserRole.LDManager
                 || CurrentUser.UserRole == Enums.UserRole.Logistic)
            {
                input.Function = "---";
            }
            var EmployeeList = _employeeBLL.GetEmployee().Where(x => x.IS_ACTIVE).ToList();
            var LocationMappingList = _locationMappingBLL.GetLocationMapping().Where(x => x.IsActive).ToList();
            if (CurrentUser.UserRole == Enums.UserRole.FinanceZone || CurrentUser.UserRole == Enums.UserRole.Logistic)
            {
                var GetCity = EmployeeList.Where(x => x.EMPLOYEE_ID == CurrentUser.EMPLOYEE_ID && x.IS_ACTIVE).FirstOrDefault();
                if (GetCity != null)
                {
                    var GetRegion = LocationMappingList.Where(x => (x.Location == null ? "" : x.Location.ToUpper()) == (GetCity.CITY == null ? "" : GetCity.CITY.ToUpper())).FirstOrDefault();
                    if (GetRegion != null)
                    {
                        input.ZoneId = GetRegion.ZoneSales;
                    }
                }
            }
            List<NoVehicleWtcDto> data = _execSummBLL.GetNoOfVehicleWtcData(input);

            var label1 = "Sales (" + data.Where(x => (x.FUNCTION == null ? "" : x.FUNCTION.ToUpper()) == "SALES").Sum(x => x.NO_OF_VEHICLE) + ")";
            var label2 = "Marketing (" + data.Where(x => (x.FUNCTION == null ? "" : x.FUNCTION.ToUpper()) == "MARKETING").Sum(x => x.NO_OF_VEHICLE) + ")";

            var groupData = data.GroupBy(x => new { x.REGIONAL })
                .Select(p => new NoVehicleWtcDto()
                {
                    REGIONAL = p.FirstOrDefault().REGIONAL,
                    NO_OF_VEHICLE_SALES = p.Where(x => (x.FUNCTION == null ? "" : x.FUNCTION.ToUpper()) == "SALES").Sum(c => c.NO_OF_VEHICLE),
                    NO_OF_VEHICLE_MARKETING = p.Where(x => (x.FUNCTION == null ? "" : x.FUNCTION.ToUpper()) == "MARKETING").Sum(c => c.NO_OF_VEHICLE),
                    LABEL1 = label1,
                    LABEL2 = label2
                }).OrderBy(x => x.REGIONAL).ToList();

            return Json(groupData);
        }

        [HttpPost]
        public JsonResult GetVehicleMakeDataVisual(int monthFrom, int? yearFrom)
        {
            var input = new VehicleMakeGetByParamInput();
            input.MonthFrom = monthFrom;
            input.YearFrom = yearFrom == null ? 0 : yearFrom.Value;
            input.MonthTo = monthFrom;
            input.YearTo = yearFrom == null ? 0 : yearFrom.Value;

            List<NoVehicleMakeDto> data = _execSummBLL.GetNoOfVehicleMakeData(input);

            var label1 = "Total (" + data.Sum(x => x.NO_OF_VEHICLE) + ")";

            var groupData = data.GroupBy(x => new { x.MANUFACTURER })
                .Select(p => new NoVehicleMakeDto()
                {
                    MANUFACTURER = p.FirstOrDefault().MANUFACTURER,
                    NO_OF_VEHICLE = p.Sum(c => c.NO_OF_VEHICLE),
                    LABEL1 = label1
                }).OrderBy(x => x.MANUFACTURER).ToList();

            return Json(groupData);
        }

        [HttpPost]
        public JsonResult GetVehicleTypeDataVisual(int monthFrom, int? yearFrom)
        {
            var input = new VehicleMakeGetByParamInput();
            input.MonthFrom = monthFrom;
            input.YearFrom = yearFrom == null ? 0 : yearFrom.Value;
            input.MonthTo = monthFrom;
            input.YearTo = yearFrom == null ? 0 : yearFrom.Value;

            List<NoVehicleMakeDto> data = _execSummBLL.GetNoOfVehicleMakeData(input);

            var label1 = "Total (" + data.Sum(x => x.NO_OF_VEHICLE) + ")";

FMS.Website/Views/RptExecutiveSummary/SumPtdByFunction.cshtml
@using FMS.Core;
@model FMS.Website.Models.SumPtdByFunctionModel

@{
	ViewBag.Title = Model.TitleForm;
}
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css" rel="stylesheet">
<style>
	.datepicker {
		margin-left: 15px;
	}
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>
<script type="text/javascript">
		$(document).ready(function () {
			$('#SearchView_YearFrom').datepicker({
			  minViewMode: 2,
			  format: 'yyyy',
			  autoclose: true,
			  position: 'right bottom',
			  container: '#xz'
			});
			$('#SearchView_YearTo').datepicker({
				minViewMode: 2,
				format: 'yyyy',
				autoclose: true,
				position: 'right bottom',
				container: '#xy'
			});
		});
</script>
<div class="opt-content clearfloat">
	<h5 class="title-page">@ViewBag.Title</h5>
	<a href="#!" class="btn btn-primary line" id="btnExport" title="Export To Excel" onclick="ExportXls()">
		<i class="fa fa-download"></i> Export
	</a>
</div>
<section class="content">
	<div class="wpanel">
		<div class="row">
			@using (Ajax.BeginForm("FilterSumPtdByFunction", "RptExecutiveSummary",
				new AjaxOptions
				{
					HttpMethod = "POST",
					InsertionMode = InsertionMode.Replace,
					UpdateTargetId = "contenttable",
					OnComplete = "setupDataTables",
					OnBegin = "LoadingShow",
					OnSuccess = "LoadingHide",
					OnFailure = "LoadingHide",
				}))
			{
				<div class="col-md-3">
					<div class="form-group">
						<label for="">Month From</label>
						@Html.DropDownListFor(model => model.SearchView.MonthFrom, Model.SearchView.MonthList, new { @class = "form-control month" })
					</div>
				</div>
				<div class="col-md-3">
					<div class="form-group" id="xz">
						<label for="">Year From</label>
						<input type="text" id="SearchView_YearFrom" value="@Model.SearchView.YearFrom" class="form-control year" data-provide="datepicker" />
					</div>
				</div>
				<div class="col-md-3">
					<div class="form-group">
						<label for="">Month To</label>
						@Html.DropDownListFor(model => model.SearchView.MonthTo, Model.SearchView.MonthList, new { @class = "form-control month" })
					</div>
				</div>
				<div class="col-md-3">
					<div class="form-group" id="xy">
						<label for="">Year To</label>
						<input type="text" id="SearchView_YearTo" value="@Model.SearchView.YearTo" class="form-control year" data-provide="datepicker" />

					</div>
				</div>
				<div class="clearfix"></div>
				<div class="col-md-3">
					<div class="form-group">
						<label for="">Vehicle Type</label>
						@Html.DropDownListFor(model => model.SearchView.VehicleType, Model.SearchView.VehicleTypeList, "ALL", new { @class = "form-control select" })
					</div>
				</div>
				<div class="col-md-3">
					<div class="form-group">
						<label for="">Regional</label>
						@Html.DropDownListFor(model => model.SearchView.Region, Model.SearchView.RegionalList, "ALL", new { @class = "form-control select" })
					</div>
				</div>
				<div class="col-md-3">
					<div class="form-group">
						<label for="">Function</label>
						@Html.HiddenFor(model => model.SearchView.FunctionId)
						@Html.DropDownListFor(model => model.SearchView.Function, Model.SearchView.Functions, new { @id = "select-function-id", @class = "chosen form-control", multiple = "multiple" })
					</div>
				</div>
				<div class="clearfix"></div>
				<div class="col-md-12">
					<button id="btn-filter" type="submit" class="btn btn-primary">Filter</button>
					<button id="btn-reset" type="button" class="btn btn-default">Reset</button>
				</div>
			}
		</div>
	</div>
	<div id="contenttable" class="wpanel">
		@Html.Partial("_ListSumPtdByFunction")
	</div>
</section>
<div id="LoadingModal" class="modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				<div align="center">
					<img src="~/Content/img/loader2.gif" id="imgLoader" style="display:block" />
				</div>
			</div>
		</div>
	</div>
</div>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Scripts/execsumscript.js"></script>
<script type="text/javascript">
    function LoadingShow() {
        $('#LoadingModal').show();
    }
    function LoadingHide() {
        $('#LoadingModal').hide();
    }
    function ExportXls() {
        console.log('Submitting');

        var theList = "";

        $("li.search-choice span").each(function (e) {
            theList += $(this).text() + ",";
        });

        theList = theList.slice(0, -1);

        var url = '@Url.Action(Model.TitleExport , "RptExecutiveSummary")';
        var getFileUrl = '@Url.Action("GetExcelFile", "RptExecutiveSummary")';
        console.log(url);
        var objToUpload =
			{
			    SearchViewExport: {
			        MonthFrom: $('#SearchView_MonthFrom').val(),
			        MonthTo: $('#SearchView_MonthTo').val(),
			        YearFrom: $('#SearchView_YearFrom').val(),
			        YearTo: $('#SearchView_YearTo').val(),
			        VehicleType: $('#SearchView_VehicleType').val(),
			        Region: $('#SearchView_Region').val(),
			        Function: theList,
			    }

			};
        $.ajax({
            url: url,
            data: JSON.stringify(objToUpload),
            contentType: 'application/json; charset=utf-8',
            beforeSend: function () {
                $('#LoadingModal').show();
            },
            success: function (response, status, jqxhr) {
                console.log("DONE");
                window.location = getFileUrl + "?pathFile=" + response;
                $('#LoadingModal').hide();
            },
            error: function (jqhxr) {
                console.log("ERROR");
                console.log(jqhxr.responseText);
                $('#LoadingModal').hide();
            },
            type: 'POST'
        });

    }

    function setupDataTables() {
        // DataTable
        var table = $('#tbSumPtdByFunction').DataTable({
            "dom": 'lf<"table-overflow"t>pi'
        });

        // Apply the search
        table.columns().eq(0).each(function (colIdx) {
            $('input', $('.filters th')[colIdx]).on('keyup change', function () {
                table
                    .column(colIdx)
                    .search(this.value)
                    .draw();
            });
        });
    }

    $(document).on('click', '#btn-reset', function () {
        var d = new Date();

        $('.month').val(d.getMonth() + 1);
        $(".year").val(d.getFullYear());
        $(".select").val('');
        $(".text").val('');

        $("#btn-filter").trigger('click');
    });

    $(function () {
        setupDataTables();
    });
</script>

FMS.Website/Views/RptExecutiveSummary/_ListAcVsOb.cshtml
@using FMS.Core
@model FMS.Website.Models.AcVsObModel

<table id="tbAcVsOb" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Function</th>
            <th>Vehicle Type</th>
            <th>Month</th>
            <th>Year</th>
            <th>Unit</th>
            <th>Cost OB</th>
            <th>Actual Cost</th>
        </tr>
    </thead>
    <thead class="filters">
        <tr>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.AcVsObDataList)
        {
            <tr>
                <td>@Html.Raw(data.Function)</td>
                <td>@Html.Raw(data.VehicleType)</td>
                <td>@Html.Raw(data.Month)</td>
                <td>@Html.Raw(data.ReportYear)</td>
                <td>@Html.Raw(data.Unit)</td>
                <td>@string.Format("{0:N0}", data.CostOb)</td>
                <td>@string.Format("{0:N0}", data.ActualCost)</td>
            </tr>
        }
    </tbody>
</table>

FMS.Website/Views/RptExecutiveSummary/_ListAccident.cshtml
@using FMS.Core
@model FMS.Website.Models.AccidentModel

<table id="tbAccident" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Vehicle Type</th>
            <th>Regional</th>
            <th>Function</th>
            <th>Month</th>
            <th>Year</th>
            <th>Accident Count</th>
        </tr>
    </thead>
    <thead class="filters">
        <tr>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.AccidentDataList)
        {
            <tr>
                <td>@Html.Raw(data.VehicleType)</td>
                <td>@Html.Raw(data.Region)</td>
                <td>@Html.Raw(data.Function)</td>
                <td>@Html.Raw(data.Month)</td>
                <td>@Html.Raw(data.ReportYear)</td>
                <td>@Html.Raw(data.AccidentCount)</td>
            </tr>
        }
    </tbody>
</table>

FMS.Website/Views/RptExecutiveSummary/_ListFuelCostByFunction.cshtml
@using FMS.Core
@model FMS.Website.Models.FuelCostByFunctionModel

<table id="tbFuelCostByFunction" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Vehicle Type</th>
            <th>Regional</th>
            <th>Function</th>
            <th>Month</th>
            <th>Year</th>
            <th>Total Fuel Cost</th>
        </tr>
    </thead>
    <thead class="filters">
        <tr>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.FuelCostByFuncDataList)
        {
            <tr>
                <td>@Html.Raw(data.VehicleType)</td>
                <td>@Html.Raw(data.Region)</td>
                <td>@Html.Raw(data.Function)</td>
                <td>@Html.Raw(data.Month)</td>
                <td>@Html.Raw(data.ReportYear)</td>
                <td>@string.Format("{0:N0}", data.TotalFuelCost)</td>
            </tr>
        }
    </tbody>
</table>

FMS.Website/Views/RptExecutiveSummary/_ListLiterByFunction.cshtml
@using FMS.Core
@model FMS.Website.Models.LiterByFunctionModel

<table id="tbLiterByFunction" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Vehicle Type</th>
            <th>Regional</th>
            <th>Function</th>
            <th>Month</th>
            <th>Year</th>
            <th>Total Liter</th>
        </tr>
    </thead>
    <thead class="filters">
        <tr>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
            <th><input type="text" style="border-radius: 7px; text-align: center; width: 100%" placeholder="Search" /></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.LiterByFuncDataList)
        {
            <tr>
                <td>@Html.Raw(data.VehicleType)</td>
                <td>@Html.Raw(data.Region)</td>
                <td>@Html.Raw(data.Function)</td>
                <td>@Html.Raw(data.Month)</td>
                <td>@Html.Raw(data.ReportYear)</td>
                <td>@string.Format("{0:N0}", data.TotalLiter)</td>
            </tr>
        }
    </tbody>
</table>